[[PCRE]]
arch = "aarch64"
git-tree-sha1 = "eefad9a55ff03a56c49b86e3774e793f6f2d31a2"
os = "macos"

    [[PCRE.download]]
    sha256 = "b3d7068a7c0144c06a8bc80bc2f42973ee127895ddbe63f9e92e5b14c36cc6f3"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.aarch64-apple-darwin.tar.gz"
[[PCRE]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "195aa2fe29e5c16a851f7772ca3e84be397e4647"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "d628e61f9024fe822fbbd4f5a43bb3c4807cabd06afd9b7ff9cf8b9724e5f3df"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PCRE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cdafd1cde51d4dee6a370448ca1588abdb8a14f"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "ed5c54a8360a96168144d71bc41fa22880b431aeff3218209e4e8c167c1a8a13"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PCRE]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f35d773acaf546577a422b4401a9719b6de9650b"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "dd982525624abc0365ce665dae8cd78678761e149708ba09c59096cf88141baa"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.aarch64-linux-musl-cxx03.tar.gz"
[[PCRE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a1d79d9944aebe2f3677db9ea4d3c2006fd2a84"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "7985cc75af12d6b472cd00401d0580400bf83f5f2e901079e72fc32d3d9e236f"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.aarch64-linux-musl-cxx11.tar.gz"
[[PCRE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f17f6ead4b5ade97132d8ad8d6e7577ca9117c7"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "35998b28313a59c3ecb65ee8786829b7fd99b94b27938b852be1b7f3ae40ca82"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PCRE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52c1f170e0b8286f719c96bbbf350d924c7d55f5"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "078a9d9c2e9c3d35bdd1ec698f8416c313f25304361d86c31be8434ffeb26e55"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PCRE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bc153f400a8196b815a828db5402f8c58c3c8c7"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "fe9ebd8b76f2d83a48b5037b8869a9f3f18e663b84db3c21286cfed8b4725e5d"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PCRE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ecfcd293e8be7453be36a7d254ee02d016e32da"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "e321c330a148d749b1d203e67464c301be0cc461312078e1b763d6dc263d7c76"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PCRE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "681d7d2b435e0a5754fd53069f116789f42949c7"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "013133aeb1fb0c88e4de1fa057a308467a31498726a285f15367d5e7223561a9"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PCRE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dca988c83b4c9d10d731ca9ca3d692668477b908"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "7db4136601d478e8c08f7d6661886e51d14b53025b3a6afd10739fda6550e9f7"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PCRE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7867a5082fe5e2f6a355920c285620aefa2f61b3"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "369c26d83761e868d8ac4e76ff3680c447f10dacd36b1819cdc643b5bf9b6c66"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PCRE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff99a4ee33d9f5fac45589c9d02ffe789938ec31"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "523140d16c1a3acbe5cd35ca8997747e4d3694575c8136981a71095532190c4f"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe72df4277254927eec3c39bbd5767d8cadcedee"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "826a0c48983d21ce29845cd2c9c2daddeb7a5641b53e767900c2572e65b93baf"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.i686-linux-gnu-cxx03.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fc7750d06efdbbc4090d039c633f1e57b16e076"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "57ea8722ea0f301feba2c0916ffdf26454de1cc98eaf8e38afc26ca58603c12b"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.i686-linux-gnu-cxx11.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f8d9778d8d746f044d4302772429c4e300cfcad"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "4a7591b0940304816d8a8a8c78c04c59264e34c94c04ccc9d2e2e98281237886"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.i686-linux-musl-cxx03.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cd5db876a787e2570e8f675b7b27b05127ca275"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "b1ea8509dbfc2dd0bb2e9554f2f1f53dfbaf3c283cf2807e9d01e52628624aa7"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.i686-linux-musl-cxx11.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58c41ee6b68d6d6a51eb4f6ca3ce7c1e081487a4"
os = "windows"

    [[PCRE.download]]
    sha256 = "985e98c18be8e063edc84d8af3a6551855b8bdd8c1ad2d97ed6c603d96cb283f"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.i686-w64-mingw32-cxx03.tar.gz"
[[PCRE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57b6b516cf4b3abf6d028e3a21a3e302f34cdd09"
os = "windows"

    [[PCRE.download]]
    sha256 = "23c7f0bb8118b3a96a888ec8943601fd3a1f8670e92793b367c39335973cd485"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.i686-w64-mingw32-cxx11.tar.gz"
[[PCRE]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05d7a749239f790017c139679160fc9ecb3114b2"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "59604cceace691d8cc3c7a0bdf7cb1c0a5b7604905aa70264fd092f650d9a5d3"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PCRE]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1eb384afe730b1df912d2a7998cf5a7e26262538"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "5b23c1140dccd56b6d4b641c61326ae2027961603183e80ac5d5cd22caa3a7cc"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PCRE]]
arch = "x86_64"
git-tree-sha1 = "a73e50010072aeaab019ee2aa427d421751a3f20"
os = "macos"

    [[PCRE.download]]
    sha256 = "ac666a131b05c2b3bbc109e2392dd185f58ec6940293fd1f3633faea9db2eec1"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.x86_64-apple-darwin.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "caf9d18c50963a5b7356c28425f55edb790b531f"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "dd519716189ab322647dd9da89cecd5d2bac35625cae0a02f7b8837859c18022"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "791ec3b0ffc89fd80adb50be4cab118dbf1d403a"
libc = "glibc"
os = "linux"

    [[PCRE.download]]
    sha256 = "6fb3c660c92e747c33698860ad4b5930026a2fd60484722ca992d513cd1df6fc"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bf4bb06047ad1e4d475df4baa68417250f89ee2"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "68c556dbeb61b92245f0b2c480a93e8cfef51893cbdf4fd9758c986593e2b536"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.x86_64-linux-musl-cxx03.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dead8d5501ffeda05c6188fb2093101e9bbd9f39"
libc = "musl"
os = "linux"

    [[PCRE.download]]
    sha256 = "f0f26c173bd6093b55268c63ff781b65310ee366b5c99bce4798d9ad58475d89"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.x86_64-linux-musl-cxx11.tar.gz"
[[PCRE]]
arch = "x86_64"
git-tree-sha1 = "e769d33f5ac77e20592840ab8377d4982eb48f01"
os = "freebsd"

    [[PCRE.download]]
    sha256 = "a3c4fd5f2cffd61946e42ad524e9d49cab748b6ed355d18e27e725d7e66a4407"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.x86_64-unknown-freebsd.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0aaf6d2ebaa287e7cb57f50daa9cf93f2e7ebf87"
os = "windows"

    [[PCRE.download]]
    sha256 = "1f7d629a22d34cee959b47f9185b012045e43d92ee12fee5a63b679acc9845c1"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PCRE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8120a27a51bf4fe1c646d7f5e995c68ba3a215b5"
os = "windows"

    [[PCRE.download]]
    sha256 = "6894f1ecaf6e7ea6e9b54b3bd00dcb558227d4401647668f6157ab3c5f0203e3"
    url = "https://github.com/JuliaBinaryWrappers/PCRE_jll.jl/releases/download/PCRE-v8.45.0+0/PCRE.v8.45.0.x86_64-w64-mingw32-cxx11.tar.gz"
